# Generated by Django 5.2.7 on 2025-10-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stripe_session_id',
            new_name='payment_id',
        ),
    ]
