# Generated by Django 5.2.7 on 2025-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripeconnectedaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('manual', 'Manual')], default='paypal', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='StripeConnectedAccount',
        ),
    ]
