# Generated by Django 5.2.7 on 2025-11-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.FloatField(blank=True, help_text='PayPal fee deducted', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_amount',
            field=models.FloatField(blank=True, help_text='Net amount received after PayPal fees', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(help_text='Total amount charged (gross)'),
        ),
    ]
