# Generated by Django 5.2.7 on 2025-11-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='amount',
        ),
        migrations.AddField(
            model_name='payout',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='payout_fee',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=10),
        ),
    ]
