# Generated by Django 5.1.7 on 2025-09-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('explorer', 'Explorer')], default='explorer', max_length=20),
        ),
    ]
