# Generated by Django 5.1.7 on 2025-09-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_blurb_user_is_email_verified_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
