# Generated by Django 5.1.7 on 2025-10-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_role_remove_user_school_user_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='links',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('default', 'Default')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
