# Generated by Django 5.1.7 on 2025-11-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_professionalprofile_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='portfolio_url',
            new_name='github',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='active_project_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='co_creator_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_color_0',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_color_1',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_funds_raised',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
