# Generated by Django 5.1.7 on 2025-11-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_linkedin_url_professionalprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/profilepics/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/profilepics/'),
        ),
    ]
