# Generated by Django 5.1.7 on 2025-11-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_professionalprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
