# Generated by Django 5.1.7 on 2025-11-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('guest', 'Guest')], default='student', max_length=20),
        ),
    ]
