# Generated by Django 5.1.7 on 2025-11-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/profilepics/'),
        ),
    ]
