"""
Django settings for Core project.
Generated by 'django-admin startproject' using Django 5.1.7.
"""
import datetime
import os
from pathlib import Path

from corsheaders.defaults import default_headers
from dotenv import load_dotenv
import dj_database_url

# === Base setup ===
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")


def csv_env(name: str, default: str = "") -> list[str]:
    return [x.strip() for x in os.getenv(name, default).split(",") if x.strip()]


# === Core settings ===
SECRET_KEY = os.getenv("SECRET_KEY", "")
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Hosts (env overrides recommended in prod)
ALLOWED_HOSTS = csv_env(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,crowdx.azurewebsites.net,.vercel.app",
)

# # === Paths / Static & Media ===
# MEDIA_ROOT = BASE_DIR / "media"
# MEDIA_URL = "/media/"

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# === Installed apps ===
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    "django.contrib.staticfiles",
    "channels",
    "storages",

    # third-party
    "corsheaders",
    "whitenoise.runserver_nostatic",
    "ninja_extra",
    "ninja_jwt",
    "ninja",

    # internal apps
    "campaigns",
    "accounts",
    "payments",
]

# === Middleware ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Core.urls"
ASGI_APPLICATION = "Core.asgi.application"
WSGI_APPLICATION = "Core.wsgi.application"

# === CORS & CSRF ===
# Frontend origins (exact) — set FRONTEND_ORIGINS / CSRF_TRUSTED in env for prod
CORS_ALLOWED_ORIGINS = csv_env(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000",
)
# Regex support for Vercel subdomains
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["authorization", "content-type"]

CSRF_TRUSTED_ORIGINS = csv_env(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,https://crowdx.azurewebsites.net",
)

# Optional: relax during local dev
if DEBUG:
    # Keep explicit origins above; this simply eases local experimentation
    CORS_ALLOW_ALL_ORIGINS = False

# === Templates ===
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# === Stripe ===
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_API_VERSION = os.getenv("STRIPE_API_VERSION", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# === Channels ===
CHANNEL_LAYERS = {
    "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
}

# === Database ===
def mssqlize(cfg: dict) -> dict:
    # Ensure mssql-django engine + common OPTIONS
    cfg["ENGINE"] = "mssql"
    opts = cfg.get("OPTIONS", {})
    opts.setdefault("driver", "ODBC Driver 18 for SQL Server")
    opts.setdefault("encrypt", True)
    opts.setdefault("trust_server_certificate", False)
    cfg["OPTIONS"] = opts
    return cfg


DATABASES: dict = {}

if os.getenv("DATABASE_URL"):
    # Single URL (preferred on Azure)
    cfg = dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
    DATABASES["default"] = mssqlize(cfg)
elif all(
    os.getenv(k)
    for k in ["DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST"]
):
    # Explicit MSSQL envs
    DATABASES["default"] = {
        "ENGINE": "mssql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "1433"),
        "OPTIONS": {
            "driver": "ODBC Driver 18 for SQL Server",
            "encrypt": os.getenv("DB_ENCRYPT", "true").lower() == "true",
            "trust_server_certificate": os.getenv("DB_TRUST_SERVER_CERT", "false").lower()
            == "true",
        },
    }
else:
    # Safe local fallback (no server ODBC needed)
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }

# === Password validation ===
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# === Internationalization ===
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# === Defaults ===
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# === JWT ===
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(hours=12),
}

# === Custom user model ===
AUTH_USER_MODEL = "accounts.User"

# === Celery (optional) ===
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "recompute-trending-every-2min": {
        "task": "campaigns.tasks.recompute_trending_scores_task",
        "schedule": 3600.0,
    },
}

# === Static files (WhiteNoise) ===
STORAGES = {
    "default": {
        # Use Azure Blob Storage for all FileField / ImageField
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
    },
    "staticfiles": {
        # You can adjust this if you use Whitenoise or ManifestStaticFilesStorage
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# === Security (reverse proxy/HTTPS on Azure) ===
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# === Misc ===
APPEND_SLASH = True
X_FRAME_OPTIONS = "DENY"

# === Azure Storage Blob Settings ===
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")
AZURE_CONTAINER = os.getenv("AZURE_CONTAINER", "media")

DEFAULT_FILE_STORAGE = os.getenv("DEFAULT_FILE_STORAGE")

MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"

