# Generated by Django 5.1.7 on 2025-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='backer_count_24h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='donation_sum_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recruiter_saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='trending_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
