# Generated by Django 5.1.7 on 2025-09-02 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_backer_count_24h_campaign_comment_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of tags', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text='Other users who are part of this campaign team', related_name='campaign_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
