# Generated by Django 5.1.7 on 2025-09-03 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_school_campaign_tags_campaign_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='milestones',
            field=models.JSONField(blank=True, help_text='List of milestone objects (title, done)', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sponsored_by',
            field=models.CharField(blank=True, help_text='Sponsor name or organization (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='backer_count_24h',
            field=models.PositiveIntegerField(default=0, help_text='New backers in last 24h'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(help_text='The primary user who created the campaign', on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total raised so far', max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='donation_sum_24h',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Donations in the last 24h', max_digits=12),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, help_text='Funding target in USD (or equivalent)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='recruiter_saves',
            field=models.PositiveIntegerField(default=0, help_text='Times this campaign was bookmarked by recruiters'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='school',
            field=models.CharField(blank=True, help_text='Optional school/university name for context', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of tags/skills/technologies', max_length=255),
        ),
    ]
