# Generated by Django 5.1.7 on 2025-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_milestones_campaign_sponsored_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
    ]
