# Generated by Django 5.1.7 on 2025-10-06 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_creator'),
        ('campaigns', '0007_remove_campaign_photos_campaignimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.creator'),
        ),
        migrations.DeleteModel(
            name='CampaignEntry',
        ),
    ]
