# Generated by Django 5.1.7 on 2025-10-25 10:17

import campaigns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_campaign_creator_delete_campaignentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaignimage',
            name='photo',
            field=models.ImageField(upload_to=campaigns.models.campaign_image_upload_to),
        ),
    ]
