# Generated by Django 5.1.7 on 2025-11-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaignmilestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.AddField(
            model_name='campaign',
            name='impact_and_future_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='implementation_progress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mentorship_or_support_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='proposed_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='technical_approach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
