# Generated by Django 5.1.7 on 2025-11-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_remove_campaign_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='outreach_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
