# Generated by Django 5.1.7 on 2025-11-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_campaign_outreach_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignmilestone',
            old_name='summary',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='campaignmilestone',
            old_name='done',
            new_name='status',
        ),
    ]
