# Generated by Django 5.1.7 on 2025-11-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_rename_summary_campaignmilestone_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='crypto_funding_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='crypto_payout_address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fiat_funding_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fiat_payout_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='use_creator_crypto_payout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='use_creator_fiat_payout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaignmilestone',
            name='milestone_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CampaignTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=128)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_links', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_team_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='team_members',
            field=models.ManyToManyField(
                related_name='campaign_memberships',
                through='campaigns.CampaignTeamMember',
                to=settings.AUTH_USER_MODEL,
                blank=True,
            ),
        ),
    ]
