# Generated by Django 5.1.7 on 2025-11-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_campaign_contact_email_campaign_contact_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='team_members',
        ),
    ]
