# Generated by Django 5.1.7 on 2025-11-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_remove_campaign_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignTeamMember',
        ),
    ]
