# Generated by Django 5.1.7 on 2025-11-08 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_delete_campaignteammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=128)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_links', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_team_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='campaign_memberships', through='campaigns.CampaignTeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
