# Generated by Django 5.1.7 on 2025-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_campaignteammember_campaign_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
        migrations.AddField(
            model_name='campaign',
            name='one_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
