# Generated by Django 5.1.7 on 2025-11-10 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_remove_campaign_slug_campaign_one_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignimage',
            name='photo',
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
        migrations.AddField(
            model_name='campaignimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
