# Generated by Django 5.1.7 on 2025-11-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_remove_campaignimage_photo_campaignimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
