# Generated by Django 5.1.7 on 2025-11-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_campaign_comments_campaign_featured_campaign_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
