# Generated by Django 5.1.7 on 2025-11-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_campaign_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='stripe_session_id',
        ),
    ]
