name: Build & Push to ACR

on:
  push:
    branches: [ fall-changes ]   # change if your default branch is different

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}   # crowdxacr.azurecr.io
  IMAGE_NAME: crowdx
  IMAGE_TAG: prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile         # adjust if your Dockerfile path differs
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
